### ISSUE TITLE
Incorrect Fonts

### ISSUE THREAD

**Issue by WinnerWinds** [saysora/p5#14]
Two fonts, notably Earwig Factory (Ransom Note Font) and Personified UX (Default Chat Theme)

Earwig Factory

![image](https://user-images.githubusercontent.com/85327029/168622543-5f8ac843-66ef-495d-bc88-35dc0210c185.png)

Personified UX

![image](https://user-images.githubusercontent.com/85327029/168622662-bbf9a4b9-3459-4eb8-a695-482f2433e25a.png)

These two fonts would be awesome to see in the theme! I hope you can implement these two fonts somehow? The font currently used feels unlike persona 5

**Comment by saysora** [comment]
Heyo.
Thanks for sharing these and sorry for not responding earlier.

I considered using the Earwig factory font and I believe the other one originally, but as time went on I found it hard to use for an app that is all reading.

I definitely will revisit implementing them.

**Comment by WinnerWinds** [comment]
Glad to see that this theme is still being worked on. No worries about the late reply

And yeah even some older Persona5 theme was very noisy, but that was because Earwig witch was used a little too much.
I feel this font would work well in very sparing areas (aka stuff like server names and all)

And i hope you have a good time programming!
