### ISSUE TITLE
text box color bug

### ISSUE THREAD

**Issue by furretkechi** [saysora/p5#16]
hi! thought i should mention that recently the text is super light in the text box!
![image](https://github.com/saysora/p5/assets/157264853/c73a70ed-cc9d-4ab2-bc48-7182a91d0e2a)
i'm not sure if its discord, the theme, or something on my end, but when having the persona theme on and selecting the darker default themes, the text is super light. however, it doesnt fix using lighter default themes because it makes the rest of the persona theme look weird. i hope this makes sense lol!

**Comment by saysora** [comment]
This should be fixed in release 1.10.0b
