### ISSUE TITLE
Font issues in different languages

### ISSUE THREAD

**Issue by saysora** [saysora/p5#2]
reported issue: 
the letter like é, è, ç à ô etc... are converted in others characters like b, d n.

**Comment by ItsFonkyBoy** [comment]
Do you know when this will be corrected?

**Comment by saysora** [comment]
> Do you know when this will be corrected?

Unfortunately not just yet. I need to write a big update already due to the updates discord does to it's theme code, but so far there's some decent edits in the version I'm at.

As well I'm not sure because I did not make the fonts being used so will need to contact the ones who did.

**Comment by saysora** [comment]
In an upcoming release the fonts have been changed entirely. I'm undecided whether we shall return to the persona 5 fonts used prior, but hopefully the new font will fix this issue. You are welcome to test out the preview build with the font changes here:

https://github.com/saysora/p5/releases/tag/1.0.3a

**Comment by saysora** [comment]
The theme revamp has now become the primary theme version so this issue should be resolved now.
