### ISSUE TITLE
Blurry Message Bar

### ISSUE THREAD

**Issue by NotSoSmartAsian** [saysora/p5#5]
When Discord is opened the message bar is HD for a few seconds and then becomes blurry low resolution. I noticed this in your screenshot so I just wanted to ask if there's a fix.

**Comment by saysora** [comment]
Are you referring to the left and right of the message bar where it's got those angles?

**Comment by NotSoSmartAsian** [comment]
I'm referring to the text in the message bar that says "Message [text channel]"

**Comment by saysora** [comment]
That should be fixed in the latest release
