### ISSUE TITLE
Permission to use this theme as base for my own theme

### ISSUE THREAD

**Issue by ZackyGameDev** [saysora/p5#8]
Hello! I have also been making [my own discord Persona 5 theme](https://user-images.githubusercontent.com/58615455/129477623-bf3d3aa4-6d69-4a3a-94f8-109e2792e3c4.png), and for that I have used your P5 theme as base since it was extremely convenient. My theme will look quite different from just yours so if I were to redistribute my theme (for free) on the internet then I need your permission for it. So is me redistributing my theme okay with you?

#### The Theme
![theTheme](https://user-images.githubusercontent.com/58615455/129477623-bf3d3aa4-6d69-4a3a-94f8-109e2792e3c4.png)

**Comment by saysora** [comment]
Completely fine with me. Best of luck to you.

**Comment by ZackyGameDev** [comment]
Thanks!
